development:
  adapter: postgresql
  encoding: unicode
  database: social_login_sandbox_development
  pool: 5
  username: baracus

test:
  adapter: postgresql
  encoding: unicode
  database: social_login_sandbox_test
  pool: 5
  username: baracus

production:
  adapter: postgresql
  encoding: unicode
  database: social_login_sandbox_production
  pool: 5
  username: baracus
